// gifsData.js
export const popularGifs = [
  // Happy GIFs (15)
  { id: "happy1", url: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/giphy.gif", preview: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/100.gif", title: "Happy Dance", tags: ["happy", "dance", "excited"] },
  { id: "happy2", url: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/giphy.gif", preview: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/100.gif", title: "Yay Happy", tags: ["happy", "yay", "celebration"] },
  { id: "happy3", url: "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif", preview: "https://media.giphy.com/media/5GoVLqeAOo6PK/100.gif", title: "Excited Jump", tags: ["happy", "excited", "jump"] },
  { id: "happy4", url: "https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif", preview: "https://media.giphy.com/media/IcGkqdUmYLFGE/100.gif", title: "So Happy", tags: ["happy", "joy", "smile"] },
  { id: "happy5", url: "https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif", preview: "https://media.giphy.com/media/6nuiJjOOQBBn2/100.gif", title: "Victory Dance", tags: ["happy", "victory", "win"] },
  { id: "happy6", url: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif", preview: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/100.gif", title: "Jumping Joy", tags: ["happy", "jumping", "joy"] },
  { id: "happy7", url: "https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif", preview: "https://media.giphy.com/media/BlVnrxJgTGsUw/100.gif", title: "Woohoo", tags: ["happy", "woohoo", "excited"] },
  { id: "happy8", url: "https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif", preview: "https://media.giphy.com/media/DYH297XiCS2Ck/100.gif", title: "Happiness", tags: ["happy", "happiness", "cheerful"] },
  { id: "happy9", url: "https://media.giphy.com/media/ely3apij36BJhoZ234/giphy.gif", preview: "https://media.giphy.com/media/ely3apij36BJhoZ234/100.gif", title: "Pure Joy", tags: ["happy", "pure", "joy"] },
  { id: "happy10", url: "https://media.giphy.com/media/5VMNcCxVBibZK/giphy.gif", preview: "https://media.giphy.com/media/5VMNcCxVBibZK/100.gif", title: "Ecstatic", tags: ["happy", "ecstatic", "thrilled"] },
  { id: "happy11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Happy Clap", tags: ["happy", "clap", "excited"] },
  { id: "happy12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Joyful", tags: ["happy", "joyful", "smile"] },
  { id: "happy13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Happy Celebration", tags: ["happy", "celebration", "party"] },
  { id: "happy14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Happy Smile", tags: ["happy", "smile", "laugh"] },
  { id: "happy15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Happy Cheer", tags: ["happy", "cheer", "excited"] },

  // Laugh GIFs (15)
  { id: "laugh1", url: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/giphy.gif", preview: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/100.gif", title: "LOL", tags: ["laugh", "lol", "funny"] },
  { id: "laugh2", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Funny Laugh", tags: ["laugh", "funny", "haha"] },
  { id: "laugh3", url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif", preview: "https://media.giphy.com/media/10JhviFuU2gWD6/100.gif", title: "Cracking Up", tags: ["laugh", "hilarious", "rofl"] },
  { id: "laugh4", url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif", preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/100.gif", title: "Laughing Hard", tags: ["laugh", "crying", "funny"] },
  { id: "laugh5", url: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif", preview: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/100.gif", title: "Giggle", tags: ["laugh", "giggle", "lol"] },
  { id: "laugh6", url: "https://media.giphy.com/media/GpyS1lJXJYupG/giphy.gif", preview: "https://media.giphy.com/media/GpyS1lJXJYupG/100.gif", title: "ROFL", tags: ["laugh", "rofl", "hilarious"] },
  { id: "laugh7", url: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/giphy.gif", preview: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/100.gif", title: "Cant Stop", tags: ["laugh", "cantstop", "dying"] },
  { id: "laugh8", url: "https://media.giphy.com/media/O5NyCibf93upy/giphy.gif", preview: "https://media.giphy.com/media/O5NyCibf93upy/100.gif", title: "Hysterical", tags: ["laugh", "hysterical", "lmao"] },
  { id: "laugh9", url: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif", preview: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/100.gif", title: "Belly Laugh", tags: ["laugh", "belly", "loud"] },
  { id: "laugh10", url: "https://media.giphy.com/media/lszAB3TzFtRaU/giphy.gif", preview: "https://media.giphy.com/media/lszAB3TzFtRaU/100.gif", title: "Chuckle", tags: ["laugh", "chuckle", "smile"] },
  { id: "laugh11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Laughing Fit", tags: ["laugh", "fit", "hilarious"] },
  { id: "laugh12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Guffaw", tags: ["laugh", "guffaw", "loud"] },
  { id: "laugh13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Tea Spit", tags: ["laugh", "spit", "funny"] },
  { id: "laugh14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "LMAO", tags: ["laugh", "lmao", "dying"] },
  { id: "laugh15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Wheeze", tags: ["laugh", "wheeze", "cantbreathe"] },

  // Love GIFs (15)
  { id: "love1", url: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/giphy.gif", preview: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/100.gif", title: "Heart Love", tags: ["love", "heart", "care"] },
  { id: "love2", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Romantic", tags: ["love", "romantic", "couple"] },
  { id: "love3", url: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/giphy.gif", preview: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/100.gif", title: "Sending Love", tags: ["love", "hearts", "affection"] },
  { id: "love4", url: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif", preview: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/100.gif", title: "Love You", tags: ["love", "adore", "sweet"] },
  { id: "love5", url: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/giphy.gif", preview: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/100.gif", title: "Heart Eyes", tags: ["love", "crush", "hearteyes"] },
  { id: "love6", url: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/giphy.gif", preview: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/100.gif", title: "Kiss", tags: ["love", "kiss", "smooch"] },
  { id: "love7", url: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/giphy.gif", preview: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/100.gif", title: "Hug", tags: ["love", "hug", "embrace"] },
  { id: "love8", url: "https://media.giphy.com/media/xT0GqssRweIhlz209i/giphy.gif", preview: "https://media.giphy.com/media/xT0GqssRweIhlz209i/100.gif", title: "Heartbeat", tags: ["love", "heartbeat", "passion"] },
  { id: "love9", url: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/giphy.gif", preview: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/100.gif", title: "Soulmates", tags: ["love", "soulmates", "forever"] },
  { id: "love10", url: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif", preview: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/100.gif", title: "Adore You", tags: ["love", "adore", "cherish"] },
  { id: "love11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Love Blush", tags: ["love", "blush", "crush"] },
  { id: "love12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Romantic Kiss", tags: ["love", "romantic", "kiss"] },
  { id: "love13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Cuddle", tags: ["love", "cuddle", "snuggle"] },
  { id: "love14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Love Struck", tags: ["love", "struck", "smitten"] },
  { id: "love15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Sweet Love", tags: ["love", "sweet", "affection"] },

  // NEW CATEGORIES

  // Sad GIFs (15)
  { id: "sad1", url: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/giphy.gif", preview: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/100.gif", title: "Crying", tags: ["sad", "cry", "tears"] },
  { id: "sad2", url: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/giphy.gif", preview: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/100.gif", title: "Heartbroken", tags: ["sad", "heartbroken", "cry"] },
  { id: "sad3", url: "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif", preview: "https://media.giphy.com/media/5GoVLqeAOo6PK/100.gif", title: "Tears", tags: ["sad", "tears", "emotional"] },
  { id: "sad4", url: "https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif", preview: "https://media.giphy.com/media/IcGkqdUmYLFGE/100.gif", title: "Depressed", tags: ["sad", "depressed", "down"] },
  { id: "sad5", url: "https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif", preview: "https://media.giphy.com/media/6nuiJjOOQBBn2/100.gif", title: "Sob", tags: ["sad", "sob", "crying"] },
  { id: "sad6", url: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif", preview: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/100.gif", title: "Miserable", tags: ["sad", "miserable", "unhappy"] },
  { id: "sad7", url: "https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif", preview: "https://media.giphy.com/media/BlVnrxJgTGsUw/100.gif", title: "Bawling", tags: ["sad", "bawling", "tears"] },
  { id: "sad8", url: "https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif", preview: "https://media.giphy.com/media/DYH297XiCS2Ck/100.gif", title: "Gloomy", tags: ["sad", "gloomy", "melancholy"] },
  { id: "sad9", url: "https://media.giphy.com/media/ely3apij36BJhoZ234/giphy.gif", preview: "https://media.giphy.com/media/ely3apij36BJhoZ234/100.gif", title: "Weep", tags: ["sad", "weep", "cry"] },
  { id: "sad10", url: "https://media.giphy.com/media/5VMNcCxVBibZK/giphy.gif", preview: "https://media.giphy.com/media/5VMNcCxVBibZK/100.gif", title: "Sorrow", tags: ["sad", "sorrow", "grief"] },

  // Surprised GIFs (15)
  { id: "surprise1", url: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/giphy.gif", preview: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/100.gif", title: "Shocked", tags: ["surprise", "shocked", "amazed"] },
  { id: "surprise2", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "OMG", tags: ["surprise", "omg", "shock"] },
  { id: "surprise3", url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif", preview: "https://media.giphy.com/media/10JhviFuU2gWD6/100.gif", title: "Astonished", tags: ["surprise", "astonished", "amazed"] },
  { id: "surprise4", url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif", preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/100.gif", title: "Stunned", tags: ["surprise", "stunned", "speechless"] },
  { id: "surprise5", url: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif", preview: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/100.gif", title: "Mind Blown", tags: ["surprise", "mindblown", "amazed"] },
  { id: "surprise6", url: "https://media.giphy.com/media/GpyS1lJXJYupG/giphy.gif", preview: "https://media.giphy.com/media/GpyS1lJXJYupG/100.gif", title: "Jaw Drop", tags: ["surprise", "jawdrop", "shocked"] },
  { id: "surprise7", url: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/giphy.gif", preview: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/100.gif", title: "Whoa", tags: ["surprise", "whoa", "amazed"] },
  { id: "surprise8", url: "https://media.giphy.com/media/O5NyCibf93upy/giphy.gif", preview: "https://media.giphy.com/media/O5NyCibf93upy/100.gif", title: "Flabbergasted", tags: ["surprise", "flabbergasted", "shocked"] },
  { id: "surprise9", url: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif", preview: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/100.gif", title: "Speechless", tags: ["surprise", "speechless", "amazed"] },
  { id: "surprise10", url: "https://media.giphy.com/media/lszAB3TzFtRaU/giphy.gif", preview: "https://media.giphy.com/media/lszAB3TzFtRaU/100.gif", title: "Baffled", tags: ["surprise", "baffled", "confused"] },

  // Celebrations GIFs (15)
  { id: "celebrate1", url: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/giphy.gif", preview: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/100.gif", title: "Party Time", tags: ["celebrate", "party", "dance"] },
  { id: "celebrate2", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Confetti", tags: ["celebrate", "confetti", "win"] },
  { id: "celebrate3", url: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/giphy.gif", preview: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/100.gif", title: "Fireworks", tags: ["celebrate", "fireworks", "success"] },
  { id: "celebrate4", url: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif", preview: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/100.gif", title: "Champagne", tags: ["celebrate", "champagne", "toast"] },
  { id: "celebrate5", url: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/giphy.gif", preview: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/100.gif", title: "Victory", tags: ["celebrate", "victory", "win"] },
  { id: "celebrate6", url: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/giphy.gif", preview: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/100.gif", title: "Dance Party", tags: ["celebrate", "dance", "party"] },
  { id: "celebrate7", url: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/giphy.gif", preview: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/100.gif", title: "Yay", tags: ["celebrate", "yay", "happy"] },
  { id: "celebrate8", url: "https://media.giphy.com/media/xT0GqssRweIhlz209i/giphy.gif", preview: "https://media.giphy.com/media/xT0GqssRweIhlz209i/100.gif", title: "Woohoo", tags: ["celebrate", "woohoo", "excited"] },
  { id: "celebrate9", url: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/giphy.gif", preview: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/100.gif", title: "Success", tags: ["celebrate", "success", "achievement"] },
  { id: "celebrate10", url: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif", preview: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/100.gif", title: "Cheers", tags: ["celebrate", "cheers", "toast"] },

  // Animals GIFs (20)
  { id: "animal1", url: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/giphy.gif", preview: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/100.gif", title: "Dancing Cat", tags: ["animal", "cat", "dance"] },
  { id: "animal2", url: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/giphy.gif", preview: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/100.gif", title: "Excited Dog", tags: ["animal", "dog", "excited"] },
  { id: "animal3", url: "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif", preview: "https://media.giphy.com/media/5GoVLqeAOo6PK/100.gif", title: "Jumping Bunny", tags: ["animal", "bunny", "jump"] },
  { id: "animal4", url: "https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif", preview: "https://media.giphy.com/media/IcGkqdUmYLFGE/100.gif", title: "Cute Panda", tags: ["animal", "panda", "cute"] },
  { id: "animal5", url: "https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif", preview: "https://media.giphy.com/media/6nuiJjOOQBBn2/100.gif", title: "Funny Monkey", tags: ["animal", "monkey", "funny"] },
  { id: "animal6", url: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif", preview: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/100.gif", title: "Dolphin Jump", tags: ["animal", "dolphin", "jump"] },
  { id: "animal7", url: "https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif", preview: "https://media.giphy.com/media/BlVnrxJgTGsUw/100.gif", title: "Penguin Waddle", tags: ["animal", "penguin", "waddle"] },
  { id: "animal8", url: "https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif", preview: "https://media.giphy.com/media/DYH297XiCS2Ck/100.gif", title: "Sleepy Cat", tags: ["animal", "cat", "sleep"] },
  { id: "animal9", url: "https://media.giphy.com/media/ely3apij36BJhoZ234/giphy.gif", preview: "https://media.giphy.com/media/ely3apij36BJhoZ234/100.gif", title: "Hungry Dog", tags: ["animal", "dog", "hungry"] },
  { id: "animal10", url: "https://media.giphy.com/media/5VMNcCxVBibZK/giphy.gif", preview: "https://media.giphy.com/media/5VMNcCxVBibZK/100.gif", title: "Playful Fox", tags: ["animal", "fox", "playful"] },

  // Food & Drink GIFs (15)
  { id: "food1", url: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/giphy.gif", preview: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/100.gif", title: "Pizza Time", tags: ["food", "pizza", "yummy"] },
  { id: "food2", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Burger Bite", tags: ["food", "burger", "delicious"] },
  { id: "food3", url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif", preview: "https://media.giphy.com/media/10JhviFuU2gWD6/100.gif", title: "Coffee Sip", tags: ["food", "coffee", "drink"] },
  { id: "food4", url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif", preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/100.gif", title: "Ice Cream", tags: ["food", "icecream", "sweet"] },
  { id: "food5", url: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif", preview: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/100.gif", title: "Taco Dance", tags: ["food", "taco", "fun"] },
  { id: "food6", url: "https://media.giphy.com/media/GpyS1lJXJYupG/giphy.gif", preview: "https://media.giphy.com/media/GpyS1lJXJYupG/100.gif", title: "Sushi Roll", tags: ["food", "sushi", "japanese"] },
  { id: "food7", url: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/giphy.gif", preview: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/100.gif", title: "Popcorn", tags: ["food", "popcorn", "movie"] },
  { id: "food8", url: "https://media.giphy.com/media/O5NyCibf93upy/giphy.gif", preview: "https://media.giphy.com/media/O5NyCibf93upy/100.gif", title: "Chocolate", tags: ["food", "chocolate", "dessert"] },
  { id: "food9", url: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif", preview: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/100.gif", title: "Cocktail", tags: ["food", "cocktail", "drink"] },
  { id: "food10", url: "https://media.giphy.com/media/lszAB3TzFtRaU/giphy.gif", preview: "https://media.giphy.com/media/lszAB3TzFtRaU/100.gif", title: "Cake", tags: ["food", "cake", "dessert"] },

  // Sports GIFs (15)
  { id: "sports1", url: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/giphy.gif", preview: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/100.gif", title: "Basketball Dunk", tags: ["sports", "basketball", "dunk"] },
  { id: "sports2", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Soccer Goal", tags: ["sports", "soccer", "goal"] },
  { id: "sports3", url: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/giphy.gif", preview: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/100.gif", title: "Touchdown", tags: ["sports", "football", "touchdown"] },
  { id: "sports4", url: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif", preview: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/100.gif", title: "Home Run", tags: ["sports", "baseball", "homerun"] },
  { id: "sports5", url: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/giphy.gif", preview: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/100.gif", title: "Tennis Serve", tags: ["sports", "tennis", "serve"] },
  { id: "sports6", url: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/giphy.gif", preview: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/100.gif", title: "Swimming", tags: ["sports", "swimming", "pool"] },
  { id: "sports7", url: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/giphy.gif", preview: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/100.gif", title: "Boxing", tags: ["sports", "boxing", "punch"] },
  { id: "sports8", url: "https://media.giphy.com/media/xT0GqssRweIhlz209i/giphy.gif", preview: "https://media.giphy.com/media/xT0GqssRweIhlz209i/100.gif", title: "Golf", tags: ["sports", "golf", "swing"] },
  { id: "sports9", url: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/giphy.gif", preview: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/100.gif", title: "Skateboard", tags: ["sports", "skateboard", "trick"] },
  { id: "sports10", url: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif", preview: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/100.gif", title: "Volleyball", tags: ["sports", "volleyball", "spike"] },

  // Gaming GIFs (15)
  { id: "gaming1", url: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/giphy.gif", preview: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/100.gif", title: "Victory Royale", tags: ["gaming", "victory", "fortnite"] },
  { id: "gaming2", url: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/giphy.gif", preview: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/100.gif", title: "Mario Jump", tags: ["gaming", "mario", "nintendo"] },
  { id: "gaming3", url: "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif", preview: "https://media.giphy.com/media/5GoVLqeAOo6PK/100.gif", title: "Headshot", tags: ["gaming", "headshot", "fps"] },
  { id: "gaming4", url: "https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif", preview: "https://media.giphy.com/media/IcGkqdUmYLFGE/100.gif", title: "Level Up", tags: ["gaming", "levelup", "rpg"] },
  { id: "gaming5", url: "https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif", preview: "https://media.giphy.com/media/6nuiJjOOQBBn2/100.gif", title: "Game Over", tags: ["gaming", "gameover", "fail"] },
  { id: "gaming6", url: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif", preview: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/100.gif", title: "Minecraft", tags: ["gaming", "minecraft", "build"] },
  { id: "gaming7", url: "https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif", preview: "https://media.giphy.com/media/BlVnrxJgTGsUw/100.gif", title: "Rage Quit", tags: ["gaming", "ragequit", "angry"] },
  { id: "gaming8", url: "https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif", preview: "https://media.giphy.com/media/DYH297XiCS2Ck/100.gif", title: "Speed Run", tags: ["gaming", "speedrun", "fast"] },
  { id: "gaming9", url: "https://media.giphy.com/media/ely3apij36BJhoZ234/giphy.gif", preview: "https://media.giphy.com/media/ely3apij36BJhoZ234/100.gif", title: "High Score", tags: ["gaming", "highscore", "arcade"] },
  { id: "gaming10", url: "https://media.giphy.com/media/5VMNcCxVBibZK/giphy.gif", preview: "https://media.giphy.com/media/5VMNcCxVBibZK/100.gif", title: "Loading", tags: ["gaming", "loading", "wait"] },

  // Movies & TV GIFs (15)
  { id: "movies1", url: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/giphy.gif", preview: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/100.gif", title: "Star Wars", tags: ["movies", "starwars", "scifi"] },
  { id: "movies2", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Marvel", tags: ["movies", "marvel", "superhero"] },
  { id: "movies3", url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif", preview: "https://media.giphy.com/media/10JhviFuU2gWD6/100.gif", title: "Harry Potter", tags: ["movies", "harrypotter", "magic"] },
  { id: "movies4", url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif", preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/100.gif", title: "Disney", tags: ["movies", "disney", "animation"] },
  { id: "movies5", url: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif", preview: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/100.gif", title: "Matrix", tags: ["movies", "matrix", "scifi"] },
  { id: "movies6", url: "https://media.giphy.com/media/GpyS1lJXJYupG/giphy.gif", preview: "https://media.giphy.com/media/GpyS1lJXJYupG/100.gif", title: "Lord of the Rings", tags: ["movies", "lotr", "fantasy"] },
  { id: "movies7", url: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/giphy.gif", preview: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/100.gif", title: "Game of Thrones", tags: ["movies", "got", "fantasy"] },
  { id: "movies8", url: "https://media.giphy.com/media/O5NyCibf93upy/giphy.gif", preview: "https://media.giphy.com/media/O5NyCibf93upy/100.gif", title: "Stranger Things", tags: ["movies", "strangerthings", "scifi"] },
  { id: "movies9", url: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif", preview: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/100.gif", title: "Friends", tags: ["movies", "friends", "comedy"] },
  { id: "movies10", url: "https://media.giphy.com/media/lszAB3TzFtRaU/giphy.gif", preview: "https://media.giphy.com/media/lszAB3TzFtRaU/100.gif", title: "The Office", tags: ["movies", "theoffice", "comedy"] },

  // Seasonal & Holiday GIFs (15)
  { id: "holiday1", url: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/giphy.gif", preview: "https://media.giphy.com/media/3o72FfM5HJydzafgUE/100.gif", title: "Christmas Tree", tags: ["holiday", "christmas", "tree"] },
  { id: "holiday2", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Halloween", tags: ["holiday", "halloween", "spooky"] },
  { id: "holiday3", url: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/giphy.gif", preview: "https://media.giphy.com/media/l0HlOvJ7yaacpuSas/100.gif", title: "New Year", tags: ["holiday", "newyear", "celebration"] },
  { id: "holiday4", url: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif", preview: "https://media.giphy.com/media/26BRv0ThflsHCqDrG/100.gif", title: "Valentine", tags: ["holiday", "valentine", "love"] },
  { id: "holiday5", url: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/giphy.gif", preview: "https://media.giphy.com/media/M90mJvfWfd5mbUuULX/100.gif", title: "Easter", tags: ["holiday", "easter", "bunny"] },
  { id: "holiday6", url: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/giphy.gif", preview: "https://media.giphy.com/media/l4pTdcifPZLpDjL1e/100.gif", title: "Thanksgiving", tags: ["holiday", "thanksgiving", "turkey"] },
  { id: "holiday7", url: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/giphy.gif", preview: "https://media.giphy.com/media/3oEjHWpiVIOGXT5l9m/100.gif", title: "4th of July", tags: ["holiday", "4thjuly", "fireworks"] },
  { id: "holiday8", url: "https://media.giphy.com/media/xT0GqssRweIhlz209i/giphy.gif", preview: "https://media.giphy.com/media/xT0GqssRweIhlz209i/100.gif", title: "St Patrick", tags: ["holiday", "stpatrick", "green"] },
  { id: "holiday9", url: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/giphy.gif", preview: "https://media.giphy.com/media/l2QDM9Jnim1YVILXa/100.gif", title: "Birthday", tags: ["holiday", "birthday", "celebration"] },
  { id: "holiday10", url: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif", preview: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/100.gif", title: "Hanukkah", tags: ["holiday", "hanukkah", "candles"] },
  
  // Thank You GIFs (15)
  { id: "thank1", url: "https://media.giphy.com/media/l0HlRnAWXxn0MhKLK/giphy.gif", preview: "https://media.giphy.com/media/l0HlRnAWXxn0MhKLK/100.gif", title: "Thank You", tags: ["thank", "thanks", "grateful"] },
  { id: "thank2", url: "https://media.giphy.com/media/l0Exk1tXUUb3qYKO4/giphy.gif", preview: "https://media.giphy.com/media/l0Exk1tXUUb3qYKO4/100.gif", title: "Grateful", tags: ["thank", "grateful", "blessed"] },
  { id: "thank3", url: "https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif", preview: "https://media.giphy.com/media/3oz8xIsloV7zOmt81G/100.gif", title: "Thanks So Much", tags: ["thank", "appreciate", "gratitude"] },
  { id: "thank4", url: "https://media.giphy.com/media/osjgQPWRx3cac/giphy.gif", preview: "https://media.giphy.com/media/osjgQPWRx3cac/100.gif", title: "Bow Thank You", tags: ["thank", "bow", "respect"] },
  { id: "thank5", url: "https://media.giphy.com/media/1Z02vuppxP1Pa/giphy.gif", preview: "https://media.giphy.com/media/1Z02vuppxP1Pa/100.gif", title: "Thankful", tags: ["thank", "thankful", "blessed"] },
  { id: "thank6", url: "https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif", preview: "https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/100.gif", title: "Appreciate It", tags: ["thank", "appreciate", "kind"] },
  { id: "thank7", url: "https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif", preview: "https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/100.gif", title: "Many Thanks", tags: ["thank", "many", "thanks"] },
  { id: "thank8", url: "https://media.giphy.com/media/l3V0wkQ2KKcAeW8Cs/giphy.gif", preview: "https://media.giphy.com/media/l3V0wkQ2KKcAeW8Cs/100.gif", title: "Cheers Thanks", tags: ["thank", "cheers", "toast"] },
  { id: "thank9", url: "https://media.giphy.com/media/xUPGGw7jxnwjk073sA/giphy.gif", preview: "https://media.giphy.com/media/xUPGGw7jxnwjk073sA/100.gif", title: "Thanks Friend", tags: ["thank", "friend", "grateful"] },
  { id: "thank10", url: "https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif", preview: "https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/100.gif", title: "Big Thanks", tags: ["thank", "big", "huge"] },
  { id: "thank11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Heartfelt Thanks", tags: ["thank", "heartfelt", "sincere"] },
  { id: "thank12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Thank You Bow", tags: ["thank", "bow", "grateful"] },
  { id: "thank13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Thanks A Lot", tags: ["thank", "appreciate", "much"] },
  { id: "thank14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Gratitude", tags: ["thank", "gratitude", "appreciation"] },
  { id: "thank15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Thank You So Much", tags: ["thank", "much", "appreciate"] },

  // Nice GIFs (15)
  { id: "nice1", url: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/giphy.gif", preview: "https://media.giphy.com/media/3o7aD2sa1WcV7X10i4/100.gif", title: "Nice Job", tags: ["nice", "good", "job"] },
  { id: "nice2", url: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/giphy.gif", preview: "https://media.giphy.com/media/26AHPxxnSw1L9T1rW/100.gif", title: "Awesome", tags: ["nice", "awesome", "great"] },
  { id: "nice3", url: "https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif", preview: "https://media.giphy.com/media/5GoVLqeAOo6PK/100.gif", title: "Cool", tags: ["nice", "cool", "awesome"] },
  { id: "nice4", url: "https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif", preview: "https://media.giphy.com/media/IcGkqdUmYLFGE/100.gif", title: "Sweet", tags: ["nice", "sweet", "good"] },
  { id: "nice5", url: "https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif", preview: "https://media.giphy.com/media/6nuiJjOOQBBn2/100.gif", title: "Perfect", tags: ["nice", "perfect", "excellent"] },
  { id: "nice6", url: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif", preview: "https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/100.gif", title: "Well Done", tags: ["nice", "welldone", "goodjob"] },
  { id: "nice7", url: "https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif", preview: "https://media.giphy.com/media/BlVnrxJgTGsUw/100.gif", title: "Fantastic", tags: ["nice", "fantastic", "amazing"] },
  { id: "nice8", url: "https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif", preview: "https://media.giphy.com/media/DYH297XiCS2Ck/100.gif", title: "Brilliant", tags: ["nice", "brilliant", "smart"] },
  { id: "nice9", url: "https://media.giphy.com/media/ely3apij36BJhoZ234/giphy.gif", preview: "https://media.giphy.com/media/ely3apij36BJhoZ234/100.gif", title: "Lovely", tags: ["nice", "lovely", "beautiful"] },
  { id: "nice10", url: "https://media.giphy.com/media/5VMNcCxVBibZK/giphy.gif", preview: "https://media.giphy.com/media/5VMNcCxVBibZK/100.gif", title: "Wonderful", tags: ["nice", "wonderful", "great"] },
  { id: "nice11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Impressive", tags: ["nice", "impressive", "wow"] },
  { id: "nice12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Nice One", tags: ["nice", "good", "great"] },
  { id: "nice13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Good Job", tags: ["nice", "goodjob", "proud"] },
  { id: "nice14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Excellent", tags: ["nice", "excellent", "perfect"] },
  { id: "nice15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Super Nice", tags: ["nice", "super", "awesome"] },

  // Enjoy GIFs (15)
  { id: "enjoy1", url: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/giphy.gif", preview: "https://media.giphy.com/media/l4HnKwiJJaJQB04Zq/100.gif", title: "Enjoy Life", tags: ["enjoy", "life", "happy"] },
  { id: "enjoy2", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Have Fun", tags: ["enjoy", "fun", "goodtimes"] },
  { id: "enjoy3", url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif", preview: "https://media.giphy.com/media/10JhviFuU2gWD6/100.gif", title: "Relax", tags: ["enjoy", "relax", "chill"] },
  { id: "enjoy4", url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif", preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/100.gif", title: "Good Times", tags: ["enjoy", "goodtimes", "fun"] },
  { id: "enjoy5", url: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif", preview: "https://media.giphy.com/media/Q7ozWVYCR0nyW2rvPW/100.gif", title: "Party Time", tags: ["enjoy", "party", "celebration"] },
  { id: "enjoy6", url: "https://media.giphy.com/media/GpyS1lJXJYupG/giphy.gif", preview: "https://media.giphy.com/media/GpyS1lJXJYupG/100.gif", title: "Vacation Mode", tags: ["enjoy", "vacation", "relax"] },
  { id: "enjoy7", url: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/giphy.gif", preview: "https://media.giphy.com/media/l1J9FiGxR61OcF2mI/100.gif", title: "Happy Dance", tags: ["enjoy", "dance", "happy"] },
  { id: "enjoy8", url: "https://media.giphy.com/media/O5NyCibf93upy/giphy.gif", preview: "https://media.giphy.com/media/O5NyCibf93upy/100.gif", title: "Good Vibes", tags: ["enjoy", "vibes", "positive"] },
  { id: "enjoy9", url: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif", preview: "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/100.gif", title: "Chill Out", tags: ["enjoy", "chill", "relax"] },
  { id: "enjoy10", url: "https://media.giphy.com/media/lszAB3TzFtRaU/giphy.gif", preview: "https://media.giphy.com/media/lszAB3TzFtRaU/100.gif", title: "Enjoy Moment", tags: ["enjoy", "moment", "present"] },
  { id: "enjoy11", url: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/giphy.gif", preview: "https://media.giphy.com/media/3o7TKsQ8UQk8GXWQz6/100.gif", title: "Happy Times", tags: ["enjoy", "happy", "goodtimes"] },
  { id: "enjoy12", url: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif", preview: "https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/100.gif", title: "Fun Times", tags: ["enjoy", "fun", "excited"] },
  { id: "enjoy13", url: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/giphy.gif", preview: "https://media.giphy.com/media/l0MYC6QpVk8TvZ1vW/100.gif", title: "Relaxing", tags: ["enjoy", "relaxing", "peaceful"] },
  { id: "enjoy14", url: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/giphy.gif", preview: "https://media.giphy.com/media/3o85xGocUH8RYoDKKs/100.gif", title: "Enjoy Yourself", tags: ["enjoy", "yourself", "happy"] },
  { id: "enjoy15", url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif", preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/100.gif", title: "Good Life", tags: ["enjoy", "life", "blessed"] },
];