const countryCode = [
  { label: "Afghanistan", value: "AF", code: "+93", iso: "AF" },
  { label: "Albania", value: "AL", code: "+355", iso: "AL" },
  { label: "Algeria", value: "DZ", code: "+213", iso: "DZ" },
  { label: "Andorra", value: "AD", code: "+376", iso: "AD" },
  { label: "Angola", value: "AO", code: "+244", iso: "AO" },
  { label: "Argentina", value: "AR", code: "+54", iso: "AR" },
  { label: "Armenia", value: "AM", code: "+374", iso: "AM" },
  { label: "Australia", value: "AU", code: "+61", iso: "AU" },
  { label: "Austria", value: "AT", code: "+43", iso: "AT" },
  { label: "Azerbaijan", value: "AZ", code: "+994", iso: "AZ" },
  { label: "Bahamas", value: "BS", code: "+1242", iso: "BS" },
  { label: "Bahrain", value: "BH", code: "+973", iso: "BH" },
  { label: "Bangladesh", value: "BD", code: "+880", iso: "BD" },
  { label: "Barbados", value: "BB", code: "+1246", iso: "BB" },
  { label: "Belarus", value: "BY", code: "+375", iso: "BY" },
  { label: "Belgium", value: "BE", code: "+32", iso: "BE" },
  { label: "Belize", value: "BZ", code: "+501", iso: "BZ" },
  { label: "Benin", value: "BJ", code: "+229", iso: "BJ" },
  { label: "Bhutan", value: "BT", code: "+975", iso: "BT" },
  { label: "Bolivia", value: "BO", code: "+591", iso: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA", code: "+387", iso: "BA" },
  { label: "Botswana", value: "BW", code: "+267", iso: "BW" },
  { label: "Brazil", value: "BR", code: "+55", iso: "BR" },
  { label: "Brunei", value: "BN", code: "+673", iso: "BN" },
  { label: "Bulgaria", value: "BG", code: "+359", iso: "BG" },
  { label: "Burkina Faso", value: "BF", code: "+226", iso: "BF" },
  { label: "Burundi", value: "BI", code: "+257", iso: "BI" },
  { label: "Cabo Verde", value: "CV", code: "+238", iso: "CV" },
  { label: "Cambodia", value: "KH", code: "+855", iso: "KH" },
  { label: "Cameroon", value: "CM", code: "+237", iso: "CM" },
  { label: "Canada", value: "CA", code: "+1", iso: "CA" },
  { label: "Central African Republic", value: "CF", code: "+236", iso: "CF" },
  { label: "Chad", value: "TD", code: "+235", iso: "TD" },
  { label: "Chile", value: "CL", code: "+56", iso: "CL" },
  { label: "China", value: "CN", code: "+86", iso: "CN" },
  { label: "Colombia", value: "CO", code: "+57", iso: "CO" },
  { label: "Comoros", value: "KM", code: "+269", iso: "KM" },
  { label: "Congo (Congo-Brazzaville)", value: "CG", code: "+242", iso: "CG" },
  {
    label: "Congo (Democratic Republic)",
    value: "CD",
    code: "+243",
    iso: "CD",
  },
  { label: "Costa Rica", value: "CR", code: "+506", iso: "CR" },
  { label: "Croatia", value: "HR", code: "+385", iso: "HR" },
  { label: "Cuba", value: "CU", code: "+53", iso: "CU" },
  { label: "Cyprus", value: "CY", code: "+357", iso: "CY" },
  { label: "Czechia", value: "CZ", code: "+420", iso: "CZ" },
  { label: "Denmark", value: "DK", code: "+45", iso: "DK" },
  { label: "Djibouti", value: "DJ", code: "+253", iso: "DJ" },
  { label: "Dominica", value: "DM", code: "+1767", iso: "DM" },
  { label: "Dominican Republic", value: "DO", code: "+1809", iso: "DO" },
  { label: "Ecuador", value: "EC", code: "+593", iso: "EC" },
  { label: "Egypt", value: "EG", code: "+20", iso: "EG" },
  { label: "El Salvador", value: "SV", code: "+503", iso: "SV" },
  { label: "Equatorial Guinea", value: "GQ", code: "+240", iso: "GQ" },
  { label: "Eritrea", value: "ER", code: "+291", iso: "ER" },
  { label: "Estonia", value: "EE", code: "+372", iso: "EE" },
  { label: "Eswatini", value: "SZ", code: "+268", iso: "SZ" },
  { label: "Ethiopia", value: "ET", code: "+251", iso: "ET" },
  { label: "Fiji", value: "FJ", code: "+679", iso: "FJ" },
  { label: "Finland", value: "FI", code: "+358", iso: "FI" },
  { label: "France", value: "FR", code: "+33", iso: "FR" },
  { label: "Gabon", value: "GA", code: "+241", iso: "GA" },
  { label: "Gambia", value: "GM", code: "+220", iso: "GM" },
  { label: "Georgia", value: "GE", code: "+995", iso: "GE" },
  { label: "Germany", value: "DE", code: "+49", iso: "DE" },
  { label: "Ghana", value: "GH", code: "+233", iso: "GH" },
  { label: "Greece", value: "GR", code: "+30", iso: "GR" },
  { label: "Grenada", value: "GD", code: "+1473", iso: "GD" },
  { label: "Guatemala", value: "GT", code: "+502", iso: "GT" },
  { label: "Guinea", value: "GN", code: "+224", iso: "GN" },
  { label: "Guinea-Bissau", value: "GW", code: "+245", iso: "GW" },
  { label: "Guyana", value: "GY", code: "+592", iso: "GY" },
  { label: "Haiti", value: "HT", code: "+509", iso: "HT" },
  { label: "Honduras", value: "HN", code: "+504", iso: "HN" },
  { label: "Hungary", value: "HU", code: "+36", iso: "HU" },
  { label: "Iceland", value: "IS", code: "+354", iso: "IS" },
  { label: "India", value: "IN", code: "+91", iso: "IN" },
  { label: "Indonesia", value: "ID", code: "+62", iso: "ID" },
  { label: "Iran", value: "IR", code: "+98", iso: "IR" },
  { label: "Iraq", value: "IQ", code: "+964", iso: "IQ" },
  { label: "Ireland", value: "IE", code: "+353", iso: "IE" },
  { label: "Israel", value: "IL", code: "+972", iso: "IL" },
  { label: "Italy", value: "IT", code: "+39", iso: "IT" },
  { label: "Jamaica", value: "JM", code: "+1876", iso: "JM" },
  { label: "Japan", value: "JP", code: "+81", iso: "JP" },
  { label: "Jordan", value: "JO", code: "+962", iso: "JO" },
  { label: "Kazakhstan", value: "KZ", code: "+7", iso: "KZ" },
  { label: "Kenya", value: "KE", code: "+254", iso: "KE" },
  { label: "Kiribati", value: "KI", code: "+686", iso: "KI" },
  { label: "Kuwait", value: "KW", code: "+965", iso: "KW" },
  { label: "Kyrgyzstan", value: "KG", code: "+996", iso: "KG" },
  { label: "Laos", value: "LA", code: "+856", iso: "LA" },
  { label: "Latvia", value: "LV", code: "+371", iso: "LV" },
  { label: "Lebanon", value: "LB", code: "+961", iso: "LB" },
  { label: "Lesotho", value: "LS", code: "+266", iso: "LS" },
  { label: "Libya", value: "LY", code: "+218", iso: "LY" },
  { label: "Liechtenstein", value: "LI", code: "+423", iso: "LI" },
  { label: "Lithuania", value: "LT", code: "+370", iso: "LT" },
  { label: "Luxembourg", value: "LU", code: "+352", iso: "LU" },
  { label: "Madagascar", value: "MG", code: "+261", iso: "MG" },
  { label: "Malawi", value: "MW", code: "+265", iso: "MW" },
  { label: "Malaysia", value: "MY", code: "+60", iso: "MY" },
  { label: "Maldives", value: "MV", code: "+960", iso: "MV" },
  { label: "Mali", value: "ML", code: "+223", iso: "ML" },
  { label: "Malta", value: "MT", code: "+356", iso: "MT" },
  { label: "Marshall Islands", value: "MH", code: "+692", iso: "MH" },
  { label: "Mauritania", value: "MR", code: "+222", iso: "MR" },
  { label: "Mauritius", value: "MU", code: "+230", iso: "MU" },
  { label: "Mexico", value: "MX", code: "+52", iso: "MX" },
  { label: "Micronesia", value: "FM", code: "+691", iso: "FM" },
  { label: "Moldova", value: "MD", code: "+373", iso: "MD" },
  { label: "Monaco", value: "MC", code: "+377", iso: "MC" },
  { label: "Mongolia", value: "MN", code: "+976", iso: "MN" },
  { label: "Montenegro", value: "ME", code: "+382", iso: "ME" },
  { label: "Morocco", value: "MA", code: "+212", iso: "MA" },
  { label: "Mozambique", value: "MZ", code: "+258", iso: "MZ" },
  { label: "Myanmar", value: "MM", code: "+95", iso: "MM" },
  { label: "Namibia", value: "NA", code: "+264", iso: "NA" },
  { label: "Nauru", value: "NR", code: "+674", iso: "NR" },
  { label: "Nepal", value: "NP", code: "+977", iso: "NP" },
  { label: "Netherlands", value: "NL", code: "+31", iso: "NL" },
  { label: "New Zealand", value: "NZ", code: "+64", iso: "NZ" },
  { label: "Nicaragua", value: "NI", code: "+505", iso: "NI" },
  { label: "Niger", value: "NE", code: "+227", iso: "NE" },
  { label: "Nigeria", value: "NG", code: "+234", iso: "NG" },
  { label: "North Korea", value: "KP", code: "+850", iso: "KP" },
  { label: "North Macedonia", value: "MK", code: "+389", iso: "MK" },
  { label: "Norway", value: "NO", code: "+47", iso: "NO" },
  { label: "Oman", value: "OM", code: "+968", iso: "OM" },
  { label: "Pakistan", value: "PK", code: "+92", iso: "PK" },
  { label: "Palau", value: "PW", code: "+680", iso: "PW" },
  { label: "Palestine", value: "PS", code: "+970", iso: "PS" },
  { label: "Panama", value: "PA", code: "+507", iso: "PA" },
  { label: "Papua New Guinea", value: "PG", code: "+675", iso: "PG" },
  { label: "Paraguay", value: "PY", code: "+595", iso: "PY" },
  { label: "Peru", value: "PE", code: "+51", iso: "PE" },
  { label: "Philippines", value: "PH", code: "+63", iso: "PH" },
  { label: "Poland", value: "PL", code: "+48", iso: "PL" },
  { label: "Portugal", value: "PT", code: "+351", iso: "PT" },
  { label: "Qatar", value: "QA", code: "+974", iso: "QA" },
  { label: "Romania", value: "RO", code: "+40", iso: "RO" },
  { label: "Russia", value: "RU", code: "+7", iso: "RU" },
  { label: "Rwanda", value: "RW", code: "+250", iso: "RW" },
  { label: "Saint Kitts and Nevis", value: "KN", code: "+1869", iso: "KN" },
  { label: "Saint Lucia", value: "LC", code: "+1758", iso: "LC" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "VC",
    code: "+1784",
    iso: "VC",
  },
  { label: "Samoa", value: "WS", code: "+685", iso: "WS" },
  { label: "San Marino", value: "SM", code: "+378", iso: "SM" },
  { label: "Sao Tome and Principe", value: "ST", code: "+239", iso: "ST" },
  { label: "Saudi Arabia", value: "SA", code: "+966", iso: "SA" },
  { label: "Senegal", value: "SN", code: "+221", iso: "SN" },
  { label: "Serbia", value: "RS", code: "+381", iso: "RS" },
  { label: "Seychelles", value: "SC", code: "+248", iso: "SC" },
  { label: "Sierra Leone", value: "SL", code: "+232", iso: "SL" },
  { label: "Singapore", value: "SG", code: "+65", iso: "SG" },
  { label: "Slovakia", value: "SK", code: "+421", iso: "SK" },
  { label: "Slovenia", value: "SI", code: "+386", iso: "SI" },
  { label: "Solomon Islands", value: "SB", code: "+677", iso: "SB" },
  { label: "Somalia", value: "SO", code: "+252", iso: "SO" },
  { label: "South Africa", value: "ZA", code: "+27", iso: "ZA" },
  { label: "South Korea", value: "KR", code: "+82", iso: "KR" },
  { label: "South Sudan", value: "SS", code: "+211", iso: "SS" },
  { label: "Spain", value: "ES", code: "+34", iso: "ES" },
  { label: "Sri Lanka", value: "LK", code: "+94", iso: "LK" },
  { label: "Sudan", value: "SD", code: "+249", iso: "SD" },
  { label: "Suriname", value: "SR", code: "+597", iso: "SR" },
  { label: "Sweden", value: "SE", code: "+46", iso: "SE" },
  { label: "Switzerland", value: "CH", code: "+41", iso: "CH" },
  { label: "Syria", value: "SY", code: "+963", iso: "SY" },
  { label: "Taiwan", value: "TW", code: "+886", iso: "TW" },
  { label: "Tajikistan", value: "TJ", code: "+992", iso: "TJ" },
  { label: "Tanzania", value: "TZ", code: "+255", iso: "TZ" },
  { label: "Thailand", value: "TH", code: "+66", iso: "TH" },
  { label: "Timor-Leste", value: "TL", code: "+670", iso: "TL" },
  { label: "Togo", value: "TG", code: "+228", iso: "TG" },
  { label: "Tonga", value: "TO", code: "+676", iso: "TO" },
  { label: "Trinidad and Tobago", value: "TT", code: "+1868", iso: "TT" },
  { label: "Tunisia", value: "TN", code: "+216", iso: "TN" },
  { label: "Turkey", value: "TR", code: "+90", iso: "TR" },
  { label: "Turkmenistan", value: "TM", code: "+993", iso: "TM" },
  { label: "Tuvalu", value: "TV", code: "+688", iso: "TV" },
  { label: "Uganda", value: "UG", code: "+256", iso: "UG" },
  { label: "Ukraine", value: "UA", code: "+380", iso: "UA" },
  { label: "United Arab Emirates", value: "AE", code: "+971", iso: "AE" },
  { label: "United Kingdom", value: "GB", code: "+44", iso: "GB" },
  { label: "United States", value: "USA", code: "+1", iso: "USA" },
  { label: "Uruguay", value: "UY", code: "+598", iso: "UY" },
  { label: "Uzbekistan", value: "UZ", code: "+998", iso: "UZ" },
  { label: "Vanuatu", value: "VU", code: "+678", iso: "VU" },
  { label: "Vatican City", value: "VA", code: "+39", iso: "VA" },
  { label: "Venezuela", value: "VE", code: "+58", iso: "VE" },
  { label: "Vietnam", value: "VN", code: "+84", iso: "VN" },
  { label: "Yemen", value: "YE", code: "+967", iso: "YE" },
  { label: "Zambia", value: "ZM", code: "+260", iso: "ZM" },
  { label: "Zimbabwe", value: "ZW", code: "+263", iso: "ZW" },
];

export default countryCode;
